export default Categories = [
    "Appetizers",
    "Beverages",
    "Breads",
    "Breakfast",
    "Brunch",
    "Budget-Friendly",
    "Cakes",
    "Casseroles",
    "Comfort Food",
    "Sauces",
    "Cookies",
    "Dairy-Free",
    "Desserts",
    "Dips/Spreads",
    "Eggs",
    "Ethnic Specific",
    "Glazes/Marinades",
    "Gluten-Free",
    "Grains",
    "Rice",
    "Grilling",
    "Barbecue",
    "Healthy",
    "Healthy Snacks",
    "Homemade Ingredients",
    "Ice Creams",
    "International Cuisines",
    "Kids",
    "Low-Carb/Keto",
    "Main Courses",
    "Meatless Mondays",
    "Mocktails",
    "One-Pot Meals",
    "Finger Foods",
    "Pasta",
    "Noodles",
    "Pies",
    "Tarts",
    "Pizza",
    "Preserves/Jams",
    "Salads",
    "Sandwiches",
    "Seafood",
    "Slow Cooker",
    "Soups",
    "Sweets",
    "Tapas",
    "Vegetarian",
    "Vegan",
    "Street Food"
]